version: "2"

linters:
  disable-all: true
  enable:
    - asciicheck
    - decorder
    - dupword
    - durationcheck
    - forcetypeassert
    - godot
    - staticcheck
    - ineffassign
    - makezero
    - misspell
    - nilerr
    - nlreturn
    - promlinter
    - reassign
    - unconvert
    - unparam
    - unused
    - usestdlibvars
    - wsl
  exclusions:
    paths:
      - ^tokenetescontroller/.*$
      - ^tokenetescontroller$
      - tokenetescontroller

formatters:
  enable:
    - gofmt
  exclusions:
    paths:
      - ^tokenetescontroller/.*$
      - ^tokenetescontroller$
      - tokenetescontroller
