version: "2"

linters:
  default: none
  enable:
    - asciicheck
    - decorder
    - dupword
    - durationcheck
    - forcetypeassert
    - godot
    - staticcheck
    - ineffassign
    - makezero
    - misspell
    - nilerr
    - nlreturn
    - promlinter
    - reassign
    - unconvert
    - unparam
    - unused
    - usestdlibvars
    - wsl_v5
  exclusions:
    paths:
      - ^tokenetescontroller/.*$
      - ^tokenetescontroller$
      - tokenetescontroller

formatters:
  enable:
    - gofmt
  exclusions:
    paths:
      - ^tokenetescontroller/.*$
      - ^tokenetescontroller$
      - tokenetescontroller
