apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: tconfigd-service-account-role
rules:
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["create", "patch"]
  - apiGroups: ["tratteria.io"]
    resources: ["trats", "tratconfigs"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["tratteria.io"]
    resources: ["trats/status", "tratconfigs/status"]
    verbs: ["update"]
