enableTratInterception: "true" # Enable or disable incoming requests interception for TraT verification
spireAgentHostDir: "/run/spire/sockets" # Host directory where the SPIRE agent's socket resides; update this if different in your environment
tratteriaSpiffeId: "spiffe://[your-trust-domain]/tratteria" # Replace "trust-domain" with your trust domain
agentHttpsApiPort: "9040" # Port number for the tratteria agent HTTPS APIs
agentHttpApiPort: "9030" # Port number for the tratteria agent HTTP APIs
agentInterceptorPort: "9050" # Port number for the tratteria agent incoming requests interceptor
