apiVersion: tratteria.io/v1alpha1
kind: TraT
metadata:
  name: order-trade-trat
  namespace: test-microservice-application
spec:
  endpoint: "/order/trade/{#stock}"
  method: "POST"
  purp: trade
  azdMapping:
    quantity:
      required: true
      value: "${body.quantity}"
    action:
      required: true
      value: "${body.action}"
    stock:
      required: true
      value: "${stock}"
  services:
    - name: order
