apiVersion: tratteria.io/v1alpha1
kind: TraT
metadata:
  name: order-trade-trat
  namespace: test-application
spec:
  endpoint: "order/trade/{#stock-id}?action={#action}"
  method: "POST"
  purp: trade
  azdMapping:
    quantity:
      required: true
      value: "${body.quantity}"
    action:
      required: true
      value: "${action}"
    stock:
      required: true
      value: "${stock-id}"
  services:
    - name: order
