apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: trats.tratteria.io
spec:
  group: tratteria.io
  names:
    kind: TraT
    plural: trats
    singular: trat
    listKind: TraTList
    shortNames:
      - trat
  scope: Namespaced
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            apiVersion:
              type: string
            kind:
              type: string
            metadata:
              type: object
            spec:
              type: object
              properties:
                endpoint:
                  type: string
                method:
                  type: string
                azd-mapping:
                  type: object
                  x-kubernetes-preserve-unknown-fields: true
                services:
                  type: array
                  items:
                    type: string
              required: ["endpoint", "method", "services"]
            status:
              type: object
              properties:
                applied:
                  type: boolean
      subresources:
        status: {}
