apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: tokenetes-agent-injector
  labels:
    tokenetes.io/webhook: "true"
webhooks:
  - name: tokenetes-agent-injector.tokenetes.io
    clientConfig:
      service:
        name: tconfigd
        namespace: tokenetes-system
        path: "/inject-tokenetes-agents"
      caBundle: 
    rules:
      - operations: ["CREATE"]
        apiGroups: [""]
        apiVersions: ["v1"]
        resources: ["pods"]
    admissionReviewVersions: ["v1", "v1beta1"]
    sideEffects: None
    timeoutSeconds: 5
    namespaceSelector:
      matchLabels:
        tokenetes-enabled: "true"
