apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: trats.tokenetes.io
spec:
  group: tokenetes.io
  names:
    kind: TraT
    plural: trats
    singular: trat
    listKind: TraTList
    shortNames:
      - trat
  scope: Namespaced
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            apiVersion:
              type: string
            kind:
              type: string
            metadata:
              type: object
            spec:
              type: object
              properties:
                path:
                  type: string
                method:
                  type: string
                purp:
                  type: string
                azdMapping:
                  type: object
                  x-kubernetes-preserve-unknown-fields: true
                services:
                  type: array
                  items:
                    type: object
                    properties:
                      name:
                        type: string
                      path:
                        type: string
                      method:
                        type: string
                      azdMapping:
                        type: object
                        x-kubernetes-preserve-unknown-fields: true
                accessEvaluation:
                  type: object
                  x-kubernetes-preserve-unknown-fields: true
              required: ["path", "method", "purp", "services"]
            status:
              type: object
              properties:
                status:
                  type: string
                  default: "PENDING"
                verificationApplied:
                  type: boolean
                generationApplied:
                  type: boolean
                lastErrorMessage:
                  type: string
                  nullable: true
                retries:
                  type: integer
                  default: 0
      additionalPrinterColumns:
        - name: "Status"
          type: "string"
          jsonPath: ".status.status"
        - name: "Age"
          type: "date"
          jsonPath: ".metadata.creationTimestamp"
          description: "Time since creation"
        - name: "Retries"
          type: "integer"
          jsonPath: ".status.retries"
      subresources:
        status: {}