name: Lint tconfigd Service

on:
  push:
    branches: [main]
    paths:
      - 'service/**'
  pull_request:
    branches: [main]
    paths:
      - 'service/**'

jobs:
  lint:
    name: Run golangci-lint on tconfigd Service
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4
        
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22.0'

      - name: List contents of the service directory
        run: ls -la ./service

      - name: Print .golangci.yml content
        run: cat ./service/.golangci.yml

      - name: Install golangci-lint
        uses: golangci/golangci-lint-action@v4
        with:
          version: v1.54.2
          args: --timeout 5m --verbose --config .golangci.yml --skip-dirs '^tratcontroller/.*$' --skip-dirs '^tratcontroller$'
          working-directory: ./service
